name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-[0-9]+"

permissions:
  contents: read

jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ncipollo/release-action@cdcc88a9acf3ca41c16c37bb7d21b9ad48560d87 # v1.15.0
        with:
          name: Release ${{ github.ref_name }}
          token: ${{ secrets.GITHUB }}

  docker:
    name: Release Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up tags
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        env:
          IMAGE_NAME: lisuke1/python-grpcio
        with:
          script: |
            const image_name = process.env.IMAGE_NAME
            const tag_name = process.env.GITHUB_REF_NAME
            let [version, sequence] = tag_name.split('-')
            if (!sequence) sequence = '0'
            const [major, minor, patch] = version.slice(1).split('.')
            const tags = [
              `${image_name}:latest`,
              `${image_name}:${major}`,
              `${image_name}:${major}.${minor}`,
              `${image_name}:${major}.${minor}.${patch}`,
              `${image_name}:${major}.${minor}.${patch}-${sequence}`
            ]
            core.exportVariable('IMAGE_TAGS', tags.join(','))

      - name: Set up QEMU
        uses: docker/setup-qemu-action@4574d27a4764455b42196d70a065bc6853246a25 # v3.4.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca # v3.9.0

      - name: Login to DockerHub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@0adf9959216b96bec444f325f1e493d4aa344497 # v6.14.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ env.IMAGE_TAGS }}
